<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
'&lt; Previous' => '&lt; Eelmine',
'&lt;&lt; First' => '&lt;&lt; Esimene',
'Get a new code' => 'Genereeri uus turvakood',
'Go to page: ' => 'Vali lehekülg: ',
'Last &gt;&gt;' => 'Viimane &gt;&gt;',
'Login Required' => 'Nõutav on sisselogimine',
'Next &gt;' => 'Järgmine &gt;',
'Please fix the following input errors:' => 'Palun paranda järgmised vead:',
'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'Faili "{file}" üleslaadimine ebaõnnestus. Lubatud on ainult järgmiste laienditega failid: {extensions}.',
'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'Fail "{file}" on liiga suur. Lubatud maksimaalne suurus on {limit} baiti.',
'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => 'Fail "{file}" on liiga väike. Lubatud minimaalne suurus on {limit} baiti.',
'The file "{file}" was only partially uploaded.' => 'Faili  "{file}" üleslaadimine õnnestus ainult osaliselt.',
'The verification code is incorrect.' => 'Sisestatud turvakood ei ole õige.',
'This content requires the <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.' => '',
'You are not authorized to perform this action.' => 'Sul pole õigusi selle toimingu sooritamiseks.',
'{attribute} "{value}" has already been taken.' => '{attribute} "{value}" on juba kasutuses.',
'{attribute} "{value}" is invalid.' => '{attribute} "{value}" ei ole korrektne.',
'{attribute} cannot be blank.' => '{attribute} ei tohi olla tühi.',
'{attribute} cannot accept more than {limit} files.' => '{attribute} limiit on {limit}.',
'{attribute} is invalid.' => '{attribute} ei ole korrektne.',
'{attribute} is not a valid URL.' => '{attribute} ei ole korrektne URL.',
'{attribute} is not a valid email address.' => '{attribute} ei ole korrektne e-posti aadress.',
'{attribute} is not in the list.' => '{attribute} ei esine etteantud nimekirjas.',
'{attribute} is of the wrong length (should be {length} characters).' => '{attribute} on vale pikkusega (peab olema {length} märki).',
'{attribute} is too big (maximum is {max}).' => '{attribute} on liiga suur (maksimum on {max}).',
'{attribute} is too long (maximum is {max} characters).' => '{attribute} on liiga pikk (maksimaalselt on lubatud {max} märki).',
'{attribute} is too short (minimum is {min} characters).' => '{attribute} on liiga lühike (minimaalselt on lubatud {min} märki).',
'{attribute} is too small (minimum is {min}).' => '{attribute} on liiga väike (miinimum on {min}).',
'{attribute} must be a number.' => '{attribute} peab olema number.',
'{attribute} must be an integer.' => '{attribute} peab olema arv.',
'{attribute} must be repeated exactly.' => '{attribute} peab täpselt kattuma.',
'{attribute} must be {type}.' => '{attribute} peab olema {type}.',
'{attribute} must be either {true} or {false}.' => '{attribute} peab olema kas {true} või {false}.',
'{attribute} must be greater than "{compareValue}".' => '{attribute} peab olema suurem kui "{compareValue}".',
'{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} peab olema suurem või võrdne "{compareValue}".',
'{attribute} must be less than "{compareValue}".' => '{attribute} peab olema väiksem kui "{compareValue}".',
'{attribute} must be less than or equal to "{compareValue}".' => '{attribute} peab olema väiksem või võrdne "{compareValue}" sein.',
'{attribute} must be {value}.' => '{attribute} peab olema {value}.',
'{attribute} must not be equal to "{compareValue}".' => '{attribute} ei tohi olla "{compareValue}".',
);
