<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
'Home' => 'Avaleht',
'The button type "{type}" is not supported.' => '',
'Are you sure to delete this item?' => 'Kas olete kindel, et soovite seda rida kustutada?',
'Delete' => 'Kustuta',
'Displaying {start}-{end} of {count} result(s).' => '{start} - {end} / {count}',
'No' => 'Ei',
'No results found.' => 'Tulemused puuduvad.',
'Not set' => 'Puudub',
'Please specify the "attributes" property.' => '',
'Please specify the "model" property.' => '',
'Sort by: ' => 'Järjesta:',
'The "dataProvider" property cannot be empty.' => '',
'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
'The property "itemView" cannot be empty.' => '',
'Total {count} result(s).' => 'Kokku {count} tulemust',
'Unknown type "{type}".' => '',
'Update' => 'Muuda',
'View' => 'Vaata',
'Yes' => 'Jah',
'{class} must specify "model" and "attribute" or "name" property values.' => '',
);
